import { getAssetUri } from '../utils/assetLoader';

export default {
    addFileOutline: getAssetUri("assets/icons/add-file-outline.png"),
    addFile: getAssetUri("assets/icons/add-file.png"),
    arrowBack: getAssetUri("assets/icons/arrow-back.png"),
    arrowDown: getAssetUri("assets/icons/arrow-down.png"),
    arrowRight: getAssetUri("assets/icons/arrow-right.png"),
    arrowUp: getAssetUri("assets/icons/arrow-up.png"),
    bag: getAssetUri("assets/icons/bag.png"),
    bellOutline: getAssetUri("assets/icons/bell-outline.png"),
    bell: getAssetUri("assets/icons/bell.png"),
    bookmarkOutline: getAssetUri("assets/icons/bookmark-outline.png"),
    bookmark: getAssetUri("assets/icons/bookmark.png"),
    calendar: getAssetUri("assets/icons/calendar.png"),
    calendar2: getAssetUri("assets/icons/calendar2.png"),
    calendar3: getAssetUri("assets/icons/calendar3.png"),
    call: getAssetUri("assets/icons/call.png"),
    categoryOutline: getAssetUri("assets/icons/category-outline.png"),
    category: getAssetUri("assets/icons/category.png"),
    chatOutline: getAssetUri("assets/icons/chat-outline.png"),
    chat: getAssetUri("assets/icons/chat.png"),
    circleDown: getAssetUri("assets/icons/circle-down.png"),
    circleLeft: getAssetUri("assets/icons/circle-left.png"),
    circleRight: getAssetUri("assets/icons/circle-right.png"),
    circleUp: getAssetUri("assets/icons/circle-up.png"),
    discountOutline: getAssetUri("assets/icons/discount-outline.png"),
    discount: getAssetUri("assets/icons/discount.png"),
    document: getAssetUri("assets/icons/document.png"),
    documentOutline: getAssetUri("assets/icons/document-outline.png"),
    downloadFile: getAssetUri("assets/icons/download-file.png"),
    email: getAssetUri("assets/icons/email.png"),
    emailOutline: getAssetUri("assets/icons/email-outline.png"),
    exploreOutline: getAssetUri("assets/icons/explore-outline.png"),
    explore: getAssetUri("assets/icons/explore.png"),
    fileUploadOutline: getAssetUri("assets/icons/file-upload-outline.png"),
    fileUpload: getAssetUri("assets/icons/file-upload.png"),
    folderOutline: getAssetUri("assets/icons/folder-outline.png"),
    folder: getAssetUri("assets/icons/folder.png"),
    graph: getAssetUri("assets/icons/graph.png"),
    graphOutline: getAssetUri("assets/icons/graph-outline.png"),
    heartOutline: getAssetUri("assets/icons/heart-outline.png"),
    heart: getAssetUri("assets/icons/heart.png"),
    hide: getAssetUri("assets/icons/hide.png"),
    home: getAssetUri("assets/icons/home.png"),
    home2: getAssetUri("assets/icons/home2.png"),
    home2Outline: getAssetUri("assets/icons/home2-outline.png"),
    image: getAssetUri("assets/icons/image.png"),
    infoCircle: getAssetUri("assets/icons/info-circle.png"),
    locationOutline,
    location,
    lock,
    lockedComputerOutline,
    logout,
    loupe,
    microphone,
    moreCircle,
    moreHorizontal,
    moreVertical,
    padlock,
    paperOutline,
    paper,
    playOutline,
    play,
    plus,
    search,
    sendOutline,
    send,
    settingOutline,
    setting2Outline,
    settings,
    shieldOutline,
    shield,
    show,
    squareInfo,
    starOutline,
    star,
    ticketOutline,
    ticket,
    timeCircle,
    trash,
    unlock,
    upAndDownArrow,
    userOutline,
    user,
    videoCameraOutline,
    videoCamera,
    voiceCommandOutline,
    voiceOutline,
    voice,
    volumeDown,
    volumeUp,
    wallet,
    walletOutline,
    wallet2,
    wallet2Outline,
    appleLogo,
    google,
    facebook,
    back,
    back2,
    arrowLeft,
    microphone2,
    microphone3,
    profile,
    content,
    download,
    download2,
    notification,
    security,
    more,
    moreInformation,
    menu,
    premium1,
    premium2,
    apple,
    paypal,
    creditCard,
    share,
    shareOutline,
    internet,
    internetOutline,
    downSquare,
    downSquare2,
    rss,
    playButton,
    pause,
    backwardPlay,
    forwardPlay,
    forwardPlay2,
    nextPlay,
    previousPlay,
    speedometer,
    speedometer2,
    stopwatch,
    cast,
    history,
    userDefault,
    userDefault2,
    userDefault3,
    bell2,
    bell3,
    email2,
    cartOutline,
    chatBubble,
    chatBubble2Outline,
    chatBubble2,
    document2Outline,
    document2,
    people,
    people2,
    people3,
    people4,
    mastercard,
    facebook2,
    headset,
    instagram,
    twitter,
    whatsapp,
    whatsapp2,
    world,
    world2,
    cart,
    search2,
    search3,
    arrowDownSquare,
    arrowUpSquare,
    cancelSquare,
    cancelSquare2,
    telephone,
    telephoneOutline,
    mediumVolume,
    noSound,
    videoCamera2,
    videoCamera2Off,
    editPencil,
    signature,
    bookmark2,
    bookmark2Outline,
    notificationBell,
    notificationBell2,
    filter,
    filter2,
    filter3,
    filter4,
    box,
    rating,
    star2,
    star3,
    star4,
    users,
    users2,
    time,
    clockTime,
    figma,
    heart2,
    heart2Outline,
    heart3,
    heart4,
    check,
    dashboardOutline,
    dashboard,
    dashboard2,
    dashboard2Outline,
    send2,
    userLocation,
    bathtub,
    bathtub2,
    bed,
    maximize,
    maximizeOutline,
    car,
    car2,
    dumbell,
    dumbell2,
    fork,
    laundry,
    pet,
    pet2,
    restaurant,
    sport,
    sport2,
    swimming,
    swimming2,
    wifi,
    wifi2,
    pin,
    pinOutline,
    calendar4,
    location2,
    location2Outline,
    location3,
    location4,
    location5,
    rightArrow,
    location7,
    addUser,
    addUserOutline,
    masterCardLogo,
    walletIcon,
    clock,
    clock2,
    crosshair,
    taxi,
    clock3,
    dotCircle,
    taxiWifi,
    motorcycle,
    close,

    bento,
    bread,
    burger,
    burger2,
    cheese,
    cookie,
    croissant,
    dessert,
    fasfFood,
    healthyDrink,
    iceCream,
    meat,
    meat2,
    noodles,
    noodles2,
    pancake,
    pizza,
    rice,
    rice2,
    salad,
    salad2,
    sandwich,
    sandwich2,
    spaghetti,
    spaghetti2,
    sushi,
    sushi2,
    taco,
    taco2,
    vegetable,
    vegetable2,
    moto,
    down,
    googleMaps,
    fundOutline,
    fundOutline2,
    fundOutline3,
    squareCheckbox,
    squareCheckbox2,
    squareCheckbox3,
    infoSquare,
    infoSquare2,
    profile2,
    car1,
    car3,
    car4,
    car5,
    parking,
    parking2,
    parking3,
    parking4,
    crown,
    crown2,
    fund,

    love,
    loveLocation,
    love2,
    group,
    friends,
    friends2,
    business,
    shoppingBag,
    plus2,
    plus3,

    loveLocation2,
    loveLocation3,
    loveLocation4,
    loveLocation5,

    idCard,
    idCardOutline,
    license,
    certificate,

    image2,
    camera,
    folder2,

    facialRecognition
}