// Use direct require for proper asset bundling by Metro/Expo
export default {
    fingerprint: require("../assets/illustrations/fingerprint.png"),
    passwordSuccess: require("../assets/illustrations/password_success.png"),
    password: require("../assets/illustrations/password.png"),
    passwordDark: require("../assets/illustrations/password_dark.png"),
    newPassword: require("../assets/illustrations/new_password.png"),
    passwordSuccessDark: require("../assets/illustrations/password_success_dark.png"),
    empty: require("../assets/illustrations/empty.png"),
    notFound: require("../assets/illustrations/not_found.png"),
    background: require("../assets/illustrations/background.png"),
    userSuccess: require("../assets/illustrations/user_success.png"),
    checked: require("../assets/illustrations/checked.png"),
    onboarding1: require("../assets/illustrations/onboarding1.png"),
    onboarding2: require("../assets/illustrations/onboarding2.png"),
    onboarding3: require("../assets/illustrations/onboarding3.png"),
    onboarding4: require("../assets/illustrations/onboarding4.png"),
    onboarding5: require("../assets/illustrations/onboarding5.png"),
    onboarding6: require("../assets/illustrations/onboarding6.png"),
    onboarding7: require("../assets/illustrations/onboarding7.png"),
    onboarding8: require("../assets/illustrations/onboarding8.png"),
    onboarding9: require("../assets/illustrations/onboarding9.png"),
    premium: require("../assets/illustrations/premium.png"),
    identity: require("../assets/illustrations/identity.png"),
    identityDark: require("../assets/illustrations/identity_dark.png"),
    card: require("../assets/illustrations/card.png")
};