// Use direct require for proper asset bundling by Metro/Expo

export default {
    ornament: require("../assets/images/ornament.png"),
    logo: require("../assets/images/logo.png"),
    logo2: require("../assets/images/logo2.png"),
    splashOnboarding: require("../assets/images/splash_onboarding.jpg"),
    user1: require("../assets/images/users/user1.jpeg"),
    user2: require("../assets/images/users/user2.jpeg"),
    user3: require("../assets/images/users/user3.jpeg"),
    user4: require("../assets/images/users/user4.jpeg"),
    user5: require("../assets/images/users/user5.jpeg"),
    user6: require("../assets/images/users/user6.jpeg"),
    user7: require("../assets/images/users/user7.jpeg"),
    user8: require("../assets/images/users/user8.jpeg"),
    user9: require("../assets/images/users/user9.jpeg"),
    user10: require("../assets/images/users/user10.jpeg"),
    user11: require("../assets/images/users/user11.jpeg"),
    menber1: require("../assets/images/menbers/user1.jpg"),
    menber2: require("../assets/images/menbers/user2.jpg"),
    menber3: require("../assets/images/menbers/user3.jpg"),
    menber4: require("../assets/images/menbers/user4.jpg"),
    menber5: require("../assets/images/menbers/user5.jpg"),
    menber6: require("../assets/images/menbers/user6.jpg"),
    menber7: require("../assets/images/menbers/user7.jpg"),
    menber8: require("../assets/images/menbers/user8.jpg"),
    model1: require("../assets/images/model1.jpg"),
    model2: require("../assets/images/model2.jpg"),
    model3: require("../assets/images/model3.jpg"),
    model4: require("../assets/images/model4.jpg"),
    elipseCard: require("../assets/images/elipse-card.png"),
    rectangleCard: require("../assets/images/rectangle-card.png"),
    backgroundAvatar1: require("../assets/images/background_avatar1.jpeg"),
    backgroundAvatar2: require("../assets/images/background_avatar2.jpeg"),
    backgroundAvatar3: require("../assets/images/background_avatar3.jpg"),
    background: require("../assets/images/background.jpg"),
    avatar: require("../assets/images/avatar.png"),
    face: require("../assets/images/face.png"),
    scanCard: require("../assets/images/scan_card.png"),
    matchCover: require("../assets/images/match_cover.png"),
    videoThumbnail: require("../assets/images/video-thumbnail.svg"),
    // Gender fallback silhouettes
    femaleSilhouette: require("../assets/images/female_silhouette.jpg"),
    maleSilhouette: require("../assets/images/male_silhouette.png")
};